### ISSUE TITLE
ipv6 record issue

### ISSUE THREAD

**Issue by cyayon** [brianreumere/gandi-automatic-dns#36] opened 2023-12-24 09:35 UTC
Hi ,

there is an issue with the new version 2.1.
the json_get_field() function failed to get the correct record_value for ipv6 records  : 

```
record_json:
---
{"rrset_name":"xxx","rrset_type":"AAAA","rrset_ttl":300,"rrset_values":["2a01:cb15:aaa:bbbb::cccc"],"rrset_href":"https://api.gandi.net/v5/livedns/domains/nbux.org/records/xxxx/AAAA"}Connecting to xxxxx
---

record_value:
---
2a01
---
```

It should be : 
```
record_value:
---
2a01:cb15:aaa:bbbb::cccc
---
```

Thanks.

**Comment by cyayon** [comment] 2023-12-24 16:14
I suggest to replace :

```
field_value=$(printf "%s" "$i" | awk -F ': ?' '{print $2}' | tr -d '"' | tr -d '[]')
```

with :
````
field_value=$(printf "%s" "$i" | cut -d: -f2- | tr -d '"' | tr -d '[]')
```

**Comment by brianreumere** [comment] 2023-12-24 16:36
Thanks for reporting this! I updated the awk field separator regex to correctly handle IPv6 addresses, and it should be fixed in https://github.com/brianreumere/gandi-automatic-dns/releases/tag/v2.1.1.

**Closed** 2023-12-24 16:36 UTC

**Comment by cyayon** [comment] 2023-12-24 16:48
Hi,

thanks.
On archlinux, with GNU awk 5.3.0, there is a warning message repeated multiple times : 

awk: warning: escape sequence `\[' treated as plain `[

Is it possible to replace : 
```
field_name=$(printf "%s" "$i" | awk -F '": ?["\[]?' '{print $1}' | tr -d '"' | tr -d '[]')
field_value=$(printf "%s" "$i" | awk -F '": ?["\[]?' '{print $2}' | tr -d '"' | tr -d '[]')
```

with
```
field_name=$(printf "%s" "$i" | awk -F '": ?["[]?' '{print $1}' | tr -d '"' | tr -d '[]')
field_value=$(printf "%s" "$i" | awk -F '": ?["[]?' '{print $2}' | tr -d '"' | tr -d '[]')
```

**Comment by brianreumere** [comment] 2023-12-24 17:48
Deleted comment that was duplicate of #37.
